# Use an official OpenJDK runtime as a parent image
FROM eclipse-temurin:21-jdk

RUN mkdir /opt/app
# Set the working directory in the container
WORKDIR /opt/app

# Copy the compiled JAR file into the container at /app
COPY target/ffmpeg-java-wrapper-1.1-SNAPSHOT.jar /opt/app/app.jar

# Expose the port that the application will run on
EXPOSE 8080

# Specify the command to run on container start
#CMD ["java", "-jar", "app.jar"]
CMD ["java", "-jar", "/opt/app/app.jar"]
